import 'package:soccer_stars/models/player.dart';

final List<Player> players = [
  const Player(
    id: 0,
    name: "Pelè",
    lastName: "Pelè",
    asset: "assets/png/pele.png",
  ),
  const Player(
    id: 1,
    name: "Diego",
    lastName: "Maradona",
    asset: "assets/png/maradona.jpg",
  ),
  const Player(
    id: 2,
    name: "Michel",
    lastName: "Platini",
    asset: "assets/png/platini.jpg",
  ),
  const Player(
    id: 3,
    name: "Franz",
    lastName: "Beckenbauer",
    asset: "assets/png/beckenbauer.jpg",
  ),
  const Player(
    id: 4,
    name: "Ronaldo",
    lastName: "Ronaldo",
    asset: "assets/png/ronaldo.jpg",
  ),
  const Player(
    id: 5,
    name: "Alfredo",
    lastName: "Di Stefano",
    asset: "assets/png/di_stefano.jpg",
  ),
  const Player(
    id: 6,
    name: "Giuseppe",
    lastName: "Meazza",
    asset: "assets/png/meazza.jpg",
  ),
  const Player(
    id: 7,
    name: "Garrincha",
    lastName: "Garrincha",
    asset: "assets/png/garrincha.jpg",
  ),
  const Player(
    id: 8,
    name: "Bobby",
    lastName: "Charlton",
    asset: "assets/png/charlton.jpg",
  ),
  const Player(
    id: 9,
    name: "Marco",
    lastName: "Van Basten",
    asset: "assets/png/van_basten.jpg",
  ),
  const Player(
    id: 10,
    name: "Zinedine",
    lastName: "Zidane",
    asset: "assets/png/zidane.jpg",
  ),
  const Player(
    id: 11,
    name: "Eusebio",
    lastName: "Eusebio",
    asset: "assets/png/eusebio.jpg",
  ),
  const Player(
    id: 12,
    name: "Franco",
    lastName: "Baresi",
    asset: "assets/png/baresi.jpg",
  ),
  const Player(
    id: 13,
    name: "Ferenc",
    lastName: "Puskàs",
    asset: "assets/png/puskàs.jpg",
  ),
  const Player(
    id: 14,
    name: "Telmo",
    lastName: "Zarra",
    asset: "assets/png/zarra.jpg",
  ),
  const Player(
    id: 15,
    name: "Gerd",
    lastName: "Muller",
    asset: "assets/png/muller.jpg",
  ),
  const Player(
    id: 16,
    name: "Matthias",
    lastName: "Sindelar",
    asset: "assets/png/sindelar.jpg",
  ),
  const Player(
    id: 17,
    name: "Jimmy",
    lastName: "Greaves",
    asset: "assets/png/greaves.jpg",
  ),
  const Player(
    id: 18,
    name: "Roberto",
    lastName: "Baggio",
    asset: "assets/png/baggio.jpg",
  ),
  const Player(
    id: 19,
    name: "Kenny",
    lastName: "Dalglish",
    asset: "assets/png/dalglish.jpg",
  ),
  const Player(
    id: 20,
    name: "Ian",
    lastName: "Rush",
    asset: "assets/png/rush.jpg",
  ),
  const Player(
    id: 21,
    name: "Roberto",
    lastName: "Carlos",
    asset: "assets/png/carlos.jpg",
  ),
  const Player(
    id: 22,
    name: "Paolo",
    lastName: "Maldini",
    asset: "assets/png/maldini.jpg",
  ),
  const Player(
    id: 23,
    name: "Raymond",
    lastName: "Kopa",
    asset: "assets/png/kopa.jpg",
  ),
  const Player(
    id: 24,
    name: "Cafu",
    lastName: "Cafu",
    asset: "assets/png/cafu.jpg",
  ),
  const Player(
    id: 25,
    name: "Ronaldinho",
    lastName: "Ronaldinho",
    asset: "assets/png/ronaldinho.jpg",
  ),
  const Player(
    id: 26,
    name: "Bobby",
    lastName: "Moore",
    asset: "assets/png/moore.jpg",
  ),
  const Player(
    id: 27,
    name: "Hugo",
    lastName: "Sanchez",
    asset: "assets/png/sanchez.jpg",
  ),
  const Player(
    id: 28,
    name: "Lothar",
    lastName: "Matthaus",
    asset: "assets/png/matthaus.jpg",
  ),
  const Player(
    id: 29,
    name: "Luis",
    lastName: "Figo",
    asset: "assets/png/figo.jpg",
  ),
  const Player(
    id: 30,
    name: "Claudio",
    lastName: "Gentile",
    asset: "assets/png/gentile.jpg",
  ),
  const Player(
    id: 31,
    name: "Jurgen",
    lastName: "Klinsmann",
    asset: "assets/png/klinsmann.jpg",
  ),
  const Player(
    id: 32,
    name: "George",
    lastName: "Best",
    asset: "assets/png/best.jpg",
  ),
  const Player(
    id: 33,
    name: "Rudi",
    lastName: "Voller",
    asset: "assets/png/voller.jpg",
  ),
  const Player(
    id: 34,
    name: "Rivaldo",
    lastName: "Rivaldo",
    asset: "assets/png/rivaldo.jpg",
  ),
  const Player(
    id: 35,
    name: "Amancio",
    lastName: "Amancio",
    asset: "assets/png/amancio.jpg",
  ),
  const Player(
    id: 36,
    name: "Denis",
    lastName: "Law",
    asset: "assets/png/law.jpg",
  ),
  const Player(
    id: 37,
    name: "Eric",
    lastName: "Cantona",
    asset: "assets/png/cantona.jpg",
  ),
  const Player(
    id: 38,
    name: "Zico",
    lastName: "Zico",
    asset: "assets/png/zico.jpg",
  ),
  const Player(
    id: 39,
    name: "Gunnar",
    lastName: "Nordahl",
    asset: "assets/png/nordahl.jpg",
  ),
  const Player(
    id: 40,
    name: "Gabriel",
    lastName: "Batistuta",
    asset: "assets/png/batistuta.jpg",
  ),
  const Player(
    id: 41,
    name: "Marcel",
    lastName: "Desailly",
    asset: "assets/png/desailly.jpg",
  ),
  const Player(
    id: 42,
    name: "Giacinto",
    lastName: "Facchetti",
    asset: "assets/png/facchetti.jpg",
  ),
  const Player(
    id: 43,
    name: "Carlos",
    lastName: "Alberto",
    asset: "assets/png/alberto.jpg",
  ),
  const Player(
    id: 44,
    name: "Giovanni",
    lastName: "Rivera",
    asset: "assets/png/rivera.jpg",
  ),
  const Player(
    id: 45,
    name: "Ronald",
    lastName: "Koeman",
    asset: "assets/png/koeman.jpg",
  ),
  const Player(
    id: 46,
    name: "Lev",
    lastName: "Yashin",
    asset: "assets/png/yashin.jpg",
  ),
  const Player(
    id: 47,
    name: "Gheorghe",
    lastName: "Hagi",
    asset: "assets/png/hagi.jpg",
  ),
  const Player(
    id: 48,
    name: "Josef",
    lastName: "Masopust",
    asset: "assets/png/masopust.jpg",
  ),
  const Player(
    id: 49,
    name: "Didi",
    lastName: "Didi",
    asset: "assets/png/didi.jpg",
  ),
  const Player(
    id: 50,
    name: "Silvio",
    lastName: "Piola",
    asset: "assets/png/piola.jpg",
  ),
  const Player(
    id: 51,
    name: "Omar",
    lastName: "Sivori",
    asset: "assets/png/sivori.jpg",
  ),
  const Player(
    id: 52,
    name: "Hans",
    lastName: "Krankl",
    asset: "assets/png/krankl.jpg",
  ),
  const Player(
    id: 53,
    name: "Luis",
    lastName: "Suarez",
    asset: "assets/png/suarez.jpg",
  ),
  const Player(
    id: 54,
    name: "Dennis",
    lastName: "Bergkamp",
    asset: "assets/png/bergkamp.jpg",
  ),
  const Player(
    id: 55,
    name: "Socrates",
    lastName: "Socrates",
    asset: "assets/png/socrates.jpg",
  ),
  const Player(
    id: 56,
    name: "Uwe",
    lastName: "Seeler",
    asset: "assets/png/seeler.jpg",
  ),
  const Player(
    id: 57,
    name: "Fabio",
    lastName: "Cannavaro",
    asset: "assets/png/cannavaro.jpg",
  ),
  const Player(
    id: 58,
    name: "Kevin",
    lastName: "Keegan",
    asset: "assets/png/keegan.jpg",
  ),
  const Player(
    id: 59,
    name: "Lillian",
    lastName: "Thuram",
    asset: "assets/png/thuram.jpg",
  ),
  const Player(
    id: 60,
    name: "Oliver",
    lastName: "Kahn",
    asset: "assets/png/kahn.jpg",
  ),
  const Player(
    id: 61,
    name: "Johann",
    lastName: "Neeskens",
    asset: "assets/png/neeskens.jpg",
  ),
  const Player(
    id: 62,
    name: "Rivelino",
    lastName: "Rivelino",
    asset: "assets/png/rivelino.jpg",
  ),
  const Player(
    id: 63,
    name: "Gordon",
    lastName: "Banks",
    asset: "assets/png/banks.jpg",
  ),
  const Player(
    id: 64,
    name: "George",
    lastName: "Weah",
    asset: "assets/png/weah.jpg",
  ),
  const Player(
    id: 65,
    name: "Stanley",
    lastName: "Matthews",
    asset: "assets/png/matthews.jpg",
  ),
  const Player(
    id: 66,
    name: "Fernando",
    lastName: "Hierro",
    asset: "assets/png/hierro.jpg",
  ),
  const Player(
    id: 67,
    name: "Dino",
    lastName: "Zoff",
    asset: "assets/png/zoff.jpg",
  ),
  const Player(
    id: 68,
    name: "Emilio",
    lastName: "Butragueno",
    asset: "assets/png/butragueno.jpg",
  ),
  const Player(
    id: 69,
    name: "Mario",
    lastName: "Kempes",
    asset: "assets/png/kempes.jpg",
  ),
  const Player(
    id: 70,
    name: "Zbigniew",
    lastName: "Boniek",
    asset: "assets/png/boniek.jpg",
  ),
  const Player(
    id: 71,
    name: "Paolo",
    lastName: "Rossi",
    asset: "assets/png/rossi.jpg",
  ),
  const Player(
    id: 72,
    name: "Alan",
    lastName: "Shearer",
    asset: "assets/png/shearer.jpg",
  ),
  const Player(
    id: 73,
    name: "Ruud",
    lastName: "Gullit",
    asset: "assets/png/gullit.jpg",
  ),
  const Player(
    id: 74,
    name: "Rui",
    lastName: "Costa",
    asset: "assets/png/сosta.jpg",
  ),
  const Player(
    id: 75,
    name: "Pavel",
    lastName: "Nedved",
    asset: "assets/png/nedved.jpg",
  ),
  const Player(
    id: 76,
    name: "Paul",
    lastName: "Gascoigne",
    asset: "assets/png/gascoigne.jpg",
  ),
  const Player(
    id: 77,
    name: "Luigi",
    lastName: "Riva",
    asset: "assets/png/riva.jpg",
  ),
  const Player(
    id: 78,
    name: "Claudio",
    lastName: "Taffarel",
    asset: "assets/png/taffarel.jpg",
  ),
  const Player(
    id: 79,
    name: "Edgar",
    lastName: "Davids",
    asset: "assets/png/davids.jpg",
  ),
  const Player(
    id: 80,
    name: "Enzo",
    lastName: "Francescoli",
    asset: "assets/png/francescoli.jpg",
  ),
];
